### ISSUE TITLE
What are the system rquirements?

### ISSUE THREAD

**Issue by bil-ash** [AI4Bharat/Chitralekha-Backend#344]
What are the system requirements(CPU cores,Ram) for performing STS using chitralekha backend on 720p video ? Also is GPU required or only CPU is enough?
Would like to know so that I understand if my current server is sufficient or I should get a better one.

**Comment by aravinth** [comment]
Hi @bil-ash 

STS requires GPU. The configuration of the GPU depends your requirement (length of the video/audio, # of parallel instances of STS processes, # of languages you are translating to, etc). May be you can start experimenting with a single A100 machine.

**Comment by bil-ash** [comment]
I tried **indictrans** on my server(without GPU) and it worked fine. So,GPU is required either for the STT or the TTS components.  I now checked the docs for indicwav2vec, indicwhisper and indictts and only indicwav2vec seems to require GPU. So if chitralekha-backend is made to use indicwhisper instead of indicwav2vec, may be we can do without GPU. 
Is this correct or am I missing something something?

**Comment by aravinth** [comment]
Currently the models are being isolated from Chitralekha application (inference happens via API endpoints). Current ASR uses the indicwav2vec model which is running on GPU. If you are able to manage any alternate without the need for GPU, then you should be good.. But I believe there would definitely be some latency issues with CPU compared to GPU. Anyway we are happy to see your experimental results with CPU.

**Comment by bil-ash** [comment]
Closing for now, will report the results if I am able to achieve some good results using CPU
